# Generated by Django 4.0.4 on 2022-04-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmbutidoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmbutidoFresco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmbutidoIberico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmbutidoSeco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Especial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FuetSalch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jamon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Legumbre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Queso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuesoImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salazones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sobrasada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('pvp', models.IntegerField()),
            ],
        ),
    ]
