# Generated by Django 4.0.4 on 2022-04-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charcuteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocido',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='conserva',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='embutidocorte',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='embutidofresco',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='embutidoiberico',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='embutidoseco',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='especial',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='fuetsalch',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='jamon',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='legumbre',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pate',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='queso',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='quesoimportacion',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='salazones',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sobrasada',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='tostas',
            name='pvp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
